name: Build and Push

on:
  push:
    branches:
      - main
      - 'prerelease-**'
    paths:
      - '.dockerignore'
      - 'Dockerfile'
      - '*.sh'
      - '.github/workflows/build-push.yml'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Get tag name prefix
        run: |
          tag_prefix=""
          if [[ "$GITHUB_REF_NAME" == prerelease-* ]]; then
            tag_prefix="${GITHUB_REF_NAME#prerelease-}-"
            echo "$tag_prefix"
          fi
          echo "TAG_NAME_PREFIX=$tag_prefix" >> "$GITHUB_ENV"

      - name: Login to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login \
            --username AWS --password-stdin public.ecr.aws

      - name: Build and push image
        run: |
          IMAGE_NAME="public.ecr.aws/${{ vars.ECR_PUBLIC_ALIAS }}/${GITHUB_REPOSITORY##*/}"
          IMAGE_TAG="${TAG_NAME_PREFIX}latest"

          docker build \
            --build-arg HELM_REPO="${{ vars.HELM_REPO }}" \
            --build-arg HELM_REPO_URL="${{ vars.HELM_REPO_URL }}" \
            -t "$IMAGE_NAME:$IMAGE_TAG" .

          docker push "$IMAGE_NAME:$IMAGE_TAG"
